### ISSUE TITLE
Picovoice Error (code `0000006F`) ,  Failed to parse AccessKey 

### ISSUE THREAD

**Issue by Scooter992** [MMRIZE/MMM-Hotword2#3]
Hi
First, thank you so much for all your work on these Magic Mirror components.    Very much appreciated.

I'm getting an access key error, probably because I don't fully understand the install instructions regarding the .env file.

directions state:
"Open the .env file (or copy from env.example), then put the accessKey into it"
Where can I find the .env file?   and what is the full name?   ie.   xxxxx.env
is this a system file somewhere for environment variables?   

I'm new to linux, hoping you can offer some more specifics.

(I've successfully run the porcupine hotword demo from their website on my Pi 4 so I know everything else works)

EDIT : I figured it out,  the .env file is a hidden file.   Hopefully this might help someone else out if they don't have hidden files turned on.      Turn

**Comment by eouia** [comment]
Sorry for late reply. `.env` file is hidden by default(That is the reason why to use it), but you can see that kind of hidden files with `ls -a` in the shell.
However, if you are stuck on only file finder (explorer) on GUI Desktop, you are right. I'll add some more description on the next update.Thanks.
